### ISSUE TITLE
Multi site and multi culture configuration

### ISSUE THREAD

**Issue by tyradeveloper** [callumbwhyte/friendly-sitemap#1]
Nice to see a package for sitemap for V8. I have a question.
Does this package supports multiple websites in one solution, having multiple cultures?

**Comment by callumbwhyte** [comment]
Hello @tyradeveloper!

Thanks for trying out Friendly Sitemap!

Yes the package absolutely does support multiple websites in one solution! Out of the box the content displayed in your sitemap.xml file will be specific to the current domain you are on.

It is also possible to have different config settings per site - please see [this documentation](https://github.com/callumbwhyte/friendly-sitemap#advanced-configuration).

Cheers,
Callum
