### ISSUE TITLE
Invalid namespace

### ISSUE THREAD

**Issue by SteveVaneeckhout** [callumbwhyte/friendly-sitemap#14]
https://github.com/callumbwhyte/friendly-sitemap/blob/58a589a72133a3764c67d5983ff9640fc04c9dd5/src/Our.Umbraco.FriendlySitemap/Builders/SitemapBuilder.cs#L11

The namespace is not valid: it should be `http://` instead of `https://`
If you look at [the schema](https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd) you will see that targetNamespace is `http://www.sitemaps.org/schemas/sitemap/0.9`

**Comment by callumbwhyte** [comment]
Hey @SteveVaneeckhout,

Thanks for using Friendly Sitemap, and thanks for raising this! A silly mistake on my part...

Thankfully @JasonElkin has resolved this and it's fixed in the latest v1.2.0 version!

Cheers,
Callum
